services:
  - type: web
    name: ine-product-price-tracker-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: SCRAPE_SHARED_SECRET
        sync: false
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/ms-playwright"
