# Generated by Django 6.1.1 on 2026-09-18 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_product_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True, max_length=500)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("brand", models.CharField(blank=True, max_length=128)),
                ("category", models.CharField(blank=True, max_length=128)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("is_tracked", models.BooleanField(db_index=True, default=True)),
                ("scrape_interval_minutes", models.IntegerField(default=120)),
                ("last_scraped_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-first_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("price_drop", "Price Drop"),
                            ("back_in_stock", "Back In Stock"),
                        ],
                        default="price_drop",
                        max_length=32,
                    ),
                ),
                (
                    "threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="tracker.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("retried_then_success", "Retried Then Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("attempt_count", models.IntegerField(default=1)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("http_or_dom_detail", models.JSONField(blank=True, default=dict)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="tracker.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("in_stock", models.BooleanField(blank=True, null=True)),
                ("stock_raw", models.CharField(blank=True, max_length=128)),
                ("scraped_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="tracker.product",
                    ),
                ),
                (
                    "scrape_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_record",
                        to="tracker.scrapelog",
                    ),
                ),
            ],
            options={
                "ordering": ["-scraped_at"],
            },
        ),
    ]
